-- 브랜드 데이터 삽입
INSERT INTO BRAND (name) VALUES ('A');
INSERT INTO BRAND (name) VALUES ('B');
INSERT INTO BRAND (name) VALUES ('C');
INSERT INTO BRAND (name) VALUES ('D');
INSERT INTO BRAND (name) VALUES ('E');
INSERT INTO BRAND (name) VALUES ('F');
INSERT INTO BRAND (name) VALUES ('G');
INSERT INTO BRAND (name) VALUES ('H');
INSERT INTO BRAND (name) VALUES ('I');
